name: Build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install npm and Jest
      run: |
        sudo apt-get install -y npm
        npm install --save-dev jest

    - name: Run tests 
      run: npm run test
